modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
logoFile="banner.png"
issueTrackerURL="https://github.com/PolarFox27/JobsMod/issues"

[[mods]]
modId="jobs"
version="${file.jarVersion}"
displayName="Jobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jobs"
credits="Thanks are to be given to TeaPix for the inspiration."
authors="PolarFox27"
description='''
Jobs is a mod that adds a highly customizable jobs system to Minecraft creating a new gameplay aspect in the game.
'''

[[dependencies.jobs]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"

[[dependencies.jobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
